version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to DevInteg
          command: . build/setup-dev.sh
      - run:
          name: Deploy Components & Run Local Tests
          command: . build/deploy-dev.sh
  deploy-uat:
    docker:
    - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Qual
          command: . build/setup-uat.sh
      - run:
          name: Deploy to Qual
          command: . build/deploy-uat.sh
workflows:
  version: 2
  validate:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy-uat:
          filters:
            branches:
              only:
                - master